[project]
name = "FoodTrack"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "szafrix", email = "bartosz.szafranski1@gmail.com"},
]
dependencies = [
    "requests>=2.32.3",
    "streamlit>=1.38.0",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
